### ISSUE TITLE
How does queue_ahead work?

### ISSUE THREAD

**Issue by MSeneadza** [simplymadeapps/simple_scheduler#12]
Hi guys,

First, let me say that I'm really looking forward to switching all my jobs over to your scheduler!  This should solve a few headaches for me.

I just added & configured the gem for a couple of my jobs.  `queue_ahead` is set to `360` in the config file.  And I have two daily tasks which are set to run at 18:10 and 18:50 (18:10 is just over an hour from now).  

Given how I interpreted `queue_ahead` to work, I expected to see two jobs scheduled in my Sidekiq dashboard: today at 18:10 and today at 18:50.  But I see 4 jobs scheduled: today and tomorrow at 18:10 and at 18:50.  Should I expect to see tomorrow's jobs scheduled already given that their start times are more than 24 hours away?

![screenshot 2017-03-16 16 59 05](https://cloud.githubusercontent.com/assets/1416050/24018350/f2b1d128-0a69-11e7-82b0-f8f06c7a7b46.png)

Thanks

**Comment by brianpattison** [comment]
Hey Michael,

I'm happy to hear that you're using Simple Scheduler and that it's solving problems for you! We love it!

The `queue_ahead` is the number of minutes that the job should the scheduled into the future, so Simple Scheduler should always make sure you have scheduled jobs for the next 6 hours. This is more true for jobs scheduled to run at an smaller interval than a day.

In your case, when you only have daily jobs, there might not be any jobs that need to be scheduled in the next 6 hours, but we make sure **there are always a minimum of 2 scheduled jobs** for each scheduled task. This ensures there is always one job in the queue that can be used to determine the next run time, even if one of the two was executed during the 10 minute Heroku Scheduler wait time.

Since you have set the `at` time, the jobs *could* be scheduled properly without extra scheduled jobs in the queue. Simple Scheduler would evaluate your config file every 10 minutes and could schedule them at the correct time by just loading your config file. But if you didn't set the `at` time, we would need to know when the last job was run to schedule the next run time correctly. Since we don't store when the last job was run, we look at the last scheduled job and use that to determine the run time of the next job and schedule it if there aren't already two scheduled jobs.

Hopefully that clears things up! 

Also, make sure you check out our blog post about why we created Simple Scheduler if you haven't: <http://www.simplymadeapps.com/blog/2017/01/simple-scheduler-schedule-recurring-tasks-to-run-at-any-interval/>

**Comment by MSeneadza** [comment]
OK, sounds good.  Thanks for the detailed response Brian. I did read your blog post before -- that's how I discovered the gem. (I think I saw it on Ruby Weekly)
