### ISSUE TITLE
Store schedule in database

### ISSUE THREAD

**Issue by sqlninja** [simplymadeapps/simple_scheduler#44]
This is simply a question:
Is it possible to run the schedule from a database rather than a yml file?

I have a had full of jobs in my yml, but sometimes I'd like to change the schedule (increase/decrease frequency) or even pause it all together. It would be nice to not have to run a deployment to affect these jobs...

**Comment by brianpattison** [comment]
It would have been much easier for Simple Scheduler to use the database to keep track of when jobs have run and when they need to run next, but we purposely didn't use the database in order to limit dependencies, to avoid needing db migrations, etc. But, I still have a possible solution for you.

I would use Simple Scheduler to run your own scheduler job that does look at the database. You just have to think of the problem a little differently. I'm not sure what interval you'd need to use, but you should be able to come up with something that works.

Here's what I'm thinking:

```yml
# Run a custom scheduler job every day at midnight
schedule_my_stuff_job:
  class: "ScheduleMyStuffJob"
  every: "1.day"
  at: "0:00"
```

```ruby
class ScheduleMyStuffJob < ApplicationJob
  def perform(scheduled_time)
    # Runs every day at midnight
    @now = Time.zone.at(scheduled_time)

    # Don't schedule anything on the weekend
    return if @now.wday == 0 || @now.wday == 6

    # Look up your settings in the database somehow
    setting = Setting.find(1)

    # Don't schedule anything if it's off completely
    return if setting.disabled?

    # Loop through to schedule the jobs for the day at the interval pulled from the db
    interval = setting.frequency_in_minutes.minutes # 60.minutes
    next_run_time = @now
    while next_run_time < 1.day.from_now(@now)
      next_run_time = interval.from_now(next_run_time)
      MyOtherJob.set(wait_until: next_run_time).perform_later
    end
  end
end
```

You'll have to figure out the interval on your own that you'd actually want this to run and load your settings data and how many jobs you want to schedule in the future, but I still think Simple Scheduler is a good fit to solve this problem. We have a bunch of jobs that spin up every 10 minutes to determine if they need to enqueue some other jobs that can't simply be scheduled run every 10 minutes on their own.

I hope this helps!

**Comment by sqlninja** [comment]
Thanks, that does give me some perspective...
I'll play around with this pattern to see if i can make it serve my needs.
I especially like the ability to 

> `# Don't schedule anything if it's off completely`
> `return if setting.disabled?`

**Comment by brianpattison** [comment]
You can probably even use the [SimpleScheduler::Task](https://www.rubydoc.info/github/simplymadeapps/simple_scheduler/SimpleScheduler/Task) class and the `future_run_times` method to help you out with your own scheduling. Let me know if you have any questions about what `SimpleScheduler::Task` is doing. It's purpose is to take the settings from the config file and determine when the next job needs to be scheduled. So if you pass it your own settings from your database, you might be able to schedule your jobs more easily that my while loop example.

**Comment by sqlninja** [comment]
Oh, that's a good call...
