### ISSUE TITLE
How necessary is the Rails requirement?

### ISSUE THREAD

**Issue by maxim** [simplymadeapps/simple_scheduler#60]
This looks like a neat well-written scheduler that would be great to use in a non-Rails app. For example, I have a use case for it now in a custom rack app. Reading through the code, I don't see all that many Rails dependencies, just a [few](https://github.com/simplymadeapps/simple_scheduler/blob/master/lib/simple_scheduler/at.rb#L31) [scattered](https://github.com/simplymadeapps/simple_scheduler/blob/master/lib/simple_scheduler/at.rb#L118) [ActiveSupport](https://github.com/simplymadeapps/simple_scheduler/blob/master/lib/simple_scheduler/task.rb#L133) [methods](https://github.com/simplymadeapps/simple_scheduler/blob/master/lib/simple_scheduler/scheduler_job.rb#L44) that could fairly easily be replaced with plain ruby counterparts. How big of a lift do you think it would be to divorce this gem from Rails, and do you have any desire for such a refactor and maintenance? I'd totally respect "no" for an answer, OSS work can be exhausting, but doesn't hurt to ask. 🙂 

**Edit:** Just to clarify, I'm not proposing removing Rails-specific support, just making the gem work without Rails as an option.

**Comment by brianpattison** [comment]
Hey @maxim,

We appreciate the kind words and I definitely agree with you that Simple Scheduler does not technically require Rails. We are using ActiveJob internally in addition to the ActiveSupport methods you pointed out, but we could get by without them... probably. It would be tough to get by without ActiveSupport. We heavily rely on the time zone support from ActiveSupport. There is a lot of code that has been tested as reliable when it comes to time zones and daylight saving time. I do not want to touch any of that! 🤢

I originally required Rails thinking I could get the job done with ActiveJob and be able to support backends other than Sidekiq. In hindsight, it would have been better to require Sidekiq and not Rails. It turns out that we rely on Sidekiq's API more than Rails. We would need a database component to get rid of Sidekiq.

That all being said, I can help you with a refactor, but we're not going to do it ourselves. We don't have the need, so we're not going to be able to dedicate the time. My biggest worry is handling the time zone/daylight saving time support. You'll want to propose a solution to that problem before you write any code if you want to tackle this.

Thanks for reaching out. Like you said, it doesn't hurt to ask!

**Comment by maxim** [comment]
Totally get the aversion to messing with timezones. 😬  And it's fair. Even if I was to go through with a refactor, I wouldn't want to put it on you to maintain it, especially considering that existing code is battle tested. Still, a great gem, thank you for making it. I found it smart how you made cautious use of the unreliable Heroku Scheduler. 👍
